In [3]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [2]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [4]:
pd.DataFrame(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

数据归一化

In [5]:
normal = MinMaxScaler()  # 实例化
result = normal.fit_transform(data)  # 数据归一化   x-min()/max()-min()

In [6]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [9]:
#逆转归一化
normal.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [7]:
# 使用numpy来实现归一化
import numpy as np
X = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])
#归一化
X_nor = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_nor

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [8]:
#逆转归一化
X_returned = X_nor * (X.max(axis=0) - X.min(axis=0)) + X.min(axis=0)
X_returned

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

数据标准化 
当数据(x)按均值(μ)中心化后，再按标准差(σ)缩放，数据就会服从为均值为0，方差为1的正态分布（即标准正态分布）

In [11]:
# 数据标准化
from sklearn.preprocessing import StandardScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = StandardScaler() #实例化
scaler.fit(data) #fit，本质是生成均值和方差
print(scaler.mean_) #查看均值的属性mean_
print(scaler.var_) #查看方差的属性var_
x_std = scaler.transform(data) #通过接口导出结果

[-0.125  9.   ]
[ 0.546875 35.      ]


In [12]:
x_std.mean() #导出的结果是一个数组，用mean()查看均值

0.0

In [13]:
x_std.std() #用std()查看方差

1.0

In [14]:
scaler.fit_transform(data)          # 使用fit_transform(data)一步达成结果
scaler.inverse_transform(x_std)     # 使用inverse_transform逆转标准化

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

处理分类型特征：编码与哑变量

In [17]:
# preprocessing.LabelEncoder：标签专用，能够将分类转换为分类数值
from sklearn.preprocessing import LabelEncoder
import pandas as pd
data = pd.read_csv(r".\data\Narrativedata.csv",index_col=0)

In [19]:
data.sample(10)

Age     Sex Embarked Survived
496  54.0  female        C      Yes
317  54.0    male        S  Unknown
100  28.0  female        S       No
194  44.0  female        C      Yes
588  22.0    male        S  Unknown
728  25.0    male        S  Unknown
571  53.0  female        S      Yes
178  30.0    male        S       No
558  39.0  female        S      Yes
16    2.0    male        Q       No

In [21]:
y = data.iloc[:,-1]                         #要输入的是标签，不是特征矩阵，所以允许一维

In [23]:
le = LabelEncoder()

In [26]:
label = le.fit_transform(y)
label

array([0, 2, 2, 2, 0, 0, 0, 0, 2, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 2, 1, 2,
       2, 2, 0, 1, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2,
       2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 1, 0,
       0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 0, 0,
       1, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0,
       2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1,
       0, 0, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2,

In [27]:
le.inverse_transform(label)  # 使用inverse_transform可以逆转

array(['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'Unknown', 'Yes', 'No', 'No', 'No', 'Unknown', 'No', 'Yes', 'No',
       'Yes', 'Unknown', 'Yes', 'Yes', 'Yes', 'No', 'Unknown', 'No', 'No',
       'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'Unknown', 'Yes', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Unknown', 'No',
       'Unknown', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'Unknown', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No',
       'Yes', 'Yes', 'No', 'Unknown', 'No', 'No', 'Yes', 'No', 'N

In [28]:
# 让标签等于我们运行出来的结果
data.iloc[:,-1] = LabelEncoder().fit_transform(data.iloc[:,-1])

In [30]:
data.sample(10)

Age     Sex Embarked  Survived
725  20.0    male        S         0
632  32.0    male        C         2
795  39.0    male        S         0
519  32.0    male        S         0
59   11.0    male        S         0
466   NaN    male        S         0
551  27.0    male        S         0
237   8.0  female        S         2
566  19.0    male        S         1
861  21.0    male        S         0

In [31]:
# preprocessing.OrdinalEncoder：特征专用，能够将分类特征转换为分类数值
from sklearn.preprocessing import OrdinalEncoder
#接口categories_对应LabelEncoder的接口classes_，一模一样的功能
data_ = data.copy()
data_.head()

Age     Sex Embarked  Survived
0  22.0    male        S         0
1  38.0  female        C         2
2  26.0  female        S         2
3  35.0  female        S         2
4  35.0    male        S         0

In [35]:
data_.loc[:,"Age"] = data_.loc[:,"Age"].fillna(data_.loc[:,"Age"].median())
#.fillna 在DataFrame里面直接进行填补
data_.dropna(axis=0,inplace=True)
#.dropna(axis=0)删除所有有缺失值的行，.dropna(axis=1)删除所有有缺失值的列
#参数inplace，为True表示在原数据集上进行修改，为False表示生成一个复制对象，不修改原数据，默认False
OrdinalEncoder().fit(data_.iloc[:,1:-1]).categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [36]:
data_.iloc[:,1:-1] = OrdinalEncoder().fit_transform(data_.iloc[:,1:-1])
data_.head()

Age  Sex  Embarked  Survived
0  22.0  1.0       2.0         0
1  38.0  0.0       0.0         2
2  26.0  0.0       2.0         2
3  35.0  0.0       2.0         2
4  35.0  1.0       2.0         0

In [38]:
# preprocessing.OneHotEncoder 独热编码
from sklearn.preprocessing import OneHotEncoder
data.loc[:,"Age"] = data.loc[:,"Age"].fillna(data.loc[:,"Age"].median())
#.fillna 在DataFrame里面直接进行填补
data.dropna(axis=0,inplace=True)

X = data.iloc[:,1:-1]
 
enc = OneHotEncoder(categories='auto').fit(X)
result = enc.transform(X).toarray()
result

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [40]:
#axis=1,表示跨行进行合并，也就是将两表左右相连，如果是axis=0，就是将量表上下相连
newdata = pd.concat([data,pd.DataFrame(result)],axis=1)
 
newdata.head()
 
newdata.drop(["Sex","Embarked"],axis=1,inplace=True)
 
newdata.columns = ["Age","Survived","Female","Male","Embarked_C","Embarked_Q","Embarked_S"]
 
newdata.sample(10)

Age  Survived  Female  Male  Embarked_C  Embarked_Q  Embarked_S
528  39.0       0.0     0.0   1.0         0.0         0.0         1.0
467  56.0       0.0     0.0   1.0         0.0         1.0         0.0
361  29.0       0.0     1.0   0.0         1.0         0.0         0.0
457  28.0       2.0     1.0   0.0         0.0         0.0         1.0
283  19.0       2.0     0.0   1.0         0.0         0.0         1.0
823  27.0       2.0     0.0   1.0         0.0         0.0         1.0
406  51.0       0.0     0.0   1.0         0.0         0.0         1.0
186  28.0       2.0     0.0   1.0         0.0         0.0         1.0
380  42.0       2.0     1.0   0.0         1.0         0.0         0.0
53   29.0       2.0     1.0   0.0         0.0         0.0         1.0

特征选择

In [48]:
#导入数据，让我们使用digit recognizor数据来一展身手
import pandas as pd

data = pd.read_csv(r"./data/digit recognizor.csv") 

In [47]:
X = data.iloc[:,1:]
y = data.iloc[:,0] 
X.shape

(42000, 784)

In [50]:
X.sample(5)

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
4259        0       0       0       0       0       0       0       0       0   
17448       0       0       0       0       0       0       0       0       0   
4136        0       0       0       0       0       0       0       0       0   
31062       0       0       0       0       0       0       0       0       0   
30403       0       0       0       0       0       0       0       0       0   

       pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
4259        0    ...            0         0         0         0         0   
17448       0    ...            0         0         0         0         0   
4136        0    ...            0         0         0         0         0   
31062       0    ...            0         0         0         0         0   
30403       0    ...            0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
4259          0         0         0         0         0  
17448         0         0         0         0         0  
4136          0         0         0         0         0  
31062         0         0         0         0         0  
30403         0         0         0         0         0  

[5 rows x 784 columns]

In [51]:
# 方差过滤  消除方差为0
from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold()                      #实例化，不填参数默认方差为0
X_var0 = selector.fit_transform(X)                  #获取删除不合格特征之后的新特征矩阵
 
#也可以直接写成 X = VairanceThreshold().fit_transform(X)
 
X_var0.shape#(42000, 708)

MemoryError: 